[workspace]
members = [
    "common-lib",
    "data-clean-batch",
    "forecast-batch",
    "forecast-server",
    "forecast-server-lib",
    "rate-gateway",
    "rate-gateway-lib",
    "training-batch",
]
