version: "3"
services:
  flyway:
    container_name: bin-option-flyway
    build:
      context: .
      dockerfile: build/Dockerfile-flyway
    volumes:
      - ./build/ddl:/flyway/sql
    env_file:
      - local.env
    networks:
      - trading-bot-network
  rate-gateway:
    container_name: bin-option-rate-gateway
    build:
      context: .
      dockerfile: build/Dockerfile-rate-gateway
    ports:
      - "8081:80"
    env_file:
      - local.env
    networks:
      - trading-bot-network
  data-clean-batch:
    container_name: bin-option-data-clean-batch
    build:
      context: .
      dockerfile: build/Dockerfile-data-clean-batch
    env_file:
      - local.env
    networks:
      - trading-bot-network
networks:
  trading-bot-network:
    external:
      name: trading-bot-network
