version: "3"
services:
  flyway:
    container_name: bin-option-flyway
    build:
      context: .
      dockerfile: build/Dockerfile-flyway
    volumes:
      - ./build/ddl:/flyway/sql
    env_file:
      - local.env
    networks:
      - trading-bot-network
  rate-gateway:
    image: ghcr.io/canpok1/bin-option-rust/rate-gateway:latest
    ports:
      - "8081:80"
    env_file:
      - local.env
    networks:
      - trading-bot-network
  data-clean-batch:
    image: ghcr.io/canpok1/bin-option-rust/data-clean-batch:latest
    environment:
      - CRON_SCHEDULE=0 0 15 * * *
      - EXPIRE_DATE_COUNT=3
    env_file:
      - local.env
    networks:
      - trading-bot-network
  training-batch:
    image: ghcr.io/canpok1/bin-option-rust/training-batch:latest
    environment:
      - CRON_SCHEDULE=0 0 16 * * Mon,Tue,Wed,Thu,Fri
    env_file:
      - local.env
    networks:
      - trading-bot-network
  forecast-server:
    image: ghcr.io/canpok1/bin-option-rust/forecast-server:latest
    ports:
      - "8082:80"
    environment:
      - RATE_EXPIRE_HOUR=12
    env_file:
      - local.env
    networks:
      - trading-bot-network
networks:
  trading-bot-network:
    external:
      name: trading-bot-network
