env_files = [
    "./local.env",
]

[tasks.build_common_lib]
description = "Build common-lib"
category = "MyCommand"
workspace = false
command = "cargo"
args = ["build", "-p", "common-lib"]


[tasks.run_forecast_server]
description = "Run forecast-server"
category = "MyCommand"
workspace = false
command = "cargo"
args = ["run", "-p", "forecast-server"]

[tasks.run_rate_gateway]
description = "Run rate-gateway"
category = "MyCommand"
workspace = false
command = "cargo"
args = ["run", "-p", "rate-gateway"]
env = { "SERVER_PORT" = "18080" }

[tasks.run_training_batch]
description = "Run training-batch"
category = "MyCommand"
workspace = false
command = "cargo"
args = ["run", "-p", "training-batch"]

[tasks.run_data_clean_batch]
description = "Run data-clean-batch"
category = "MyCommand"
workspace = false
command = "cargo"
args = ["run", "-p", "data-clean-batch"]


[tasks.generate_rate_gateway_lib]
description = "Generate rate-gateway-lib"
category = "MyCommand"
workspace = false
command = "openapi-generator-cli"
args = ["generate", "-g", "rust-server", "-i", "docs/rate-gateway.yaml", "-o", "rate-gateway-lib", "--package-name", "rate-gateway-lib"]

[tasks.generate_forecast_server_lib]
description = "Generate forecast-server-lib"
category = "MyCommand"
workspace = false
command = "openapi-generator-cli"
args = ["generate", "-g", "rust-server", "-i", "docs/forecast-server.yaml", "-o", "forecast-server-lib", "--package-name", "forecast-server-lib"]
