openapi: 3.0.0
info:
  license:
    name: MIT
  title: RateGateway
  version: 1.0.0
servers:
- url: http://localhost:18080/
tags:
- description: レート関連
  name: rates
paths:
  /rates/{pair}:
    post:
      parameters:
      - description: 通貨ペア
        explode: false
        in: path
        name: pair
        required: true
        schema:
          enum:
          - USDJPY
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              description: レートのリスト
              items:
                $ref: '#/components/schemas/Rate'
              type: array
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostSuccess'
          description: 登録成功
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（リクエストパラメータ不備）
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（通貨ペアが非対応）
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（内部エラー）
      summary: レートを新規登録します
      tags:
      - rates
components:
  schemas:
    Rate:
      description: レート
      example:
        time: time
        value: 0.8008281904610115
      properties:
        time:
          description: レートの日時
          format: dateTime
          type: string
        value:
          description: レートの値
          format: double
          type: number
      required:
      - time
      - value
      type: object
    PostSuccess:
      description: Post成功時の情報
      example:
        count: 0
      properties:
        count:
          description: 登録数
          format: int64
          type: integer
      required:
      - count
      type: object
    Error:
      description: エラー情報
      properties:
        message:
          description: エラーメッセージ
          type: string
      required:
      - message
      type: object

