openapi: 3.0.0
info:
  license:
    name: MIT
  title: ForecastServer
  version: 1.0.0
servers:
- url: http://localhost:8082/
tags:
- description: レート関連
  name: rates
paths:
  /rates:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_rates_post_201_response'
          description: 登録成功
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（リクエストパラメータ不備）
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（通貨ペアが非対応）
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 登録失敗（内部エラー）
      summary: レート履歴を新規登録します
      tags:
      - rates
  /forecast/after30min/{rateId}/{modelNo}:
    get:
      parameters:
      - description: レート履歴ID
        explode: false
        in: path
        name: rateId
        required: true
        schema:
          type: string
        style: simple
      - description: モデルNo
        explode: false
        in: path
        name: modelNo
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_forecast_after30min__rateId___modelNo__get_200_response'
          description: 取得成功
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 取得失敗（レート情報もしくはモデルが見つからない）
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 取得失敗（内部エラー）
      summary: 30分後の予想を取得します
      tags:
      - rates
components:
  schemas:
    ForecastResult:
      description: 予測結果
      example:
        rate: 0.8008281904610115
        rmse: 6.027456183070403
        complete: true
      properties:
        complete:
          description: 予測が完了したか？
          type: boolean
        rate:
          description: レートの値
          format: double
          type: number
        rmse:
          description: 予測モデルのRMSE
          format: double
          type: number
      required:
      - complete
      type: object
    History:
      description: レート履歴
      example:
        pair: USDJPY
        rate_histories:
        - 0.8008281904610115
        - 0.8008281904610115
      properties:
        pair:
          description: 通貨ペア
          enum:
          - USDJPY
          type: string
        rate_histories:
          items:
            description: レートの履歴（先頭が過去）
            format: double
            type: number
          type: array
      required:
      - pair
      - rate_histories
      type: object
    Error:
      description: エラー情報
      properties:
        message:
          description: エラーメッセージ
          type: string
      required:
      - message
      type: object
    _rates_post_201_response:
      description: 成功時の情報
      example:
        expire: expire
        rateId: rateId
      properties:
        rateId:
          description: レート履歴ID
          type: string
        expire:
          description: 有効期限
          format: dateTime
          type: string
      required:
      - expire
      - rateId
      type: object
    _forecast_after30min__rateId___modelNo__get_200_response:
      description: 成功時の情報
      example:
        result:
          rate: 0.8008281904610115
          rmse: 6.027456183070403
          complete: true
      properties:
        result:
          $ref: '#/components/schemas/ForecastResult'
      required:
      - rate
      type: object

