openapi: "3.0.0"
info:
  version: 1.0.0
  title: ForecastServer
  license:
    name: MIT
servers:
  - url: http://localhost:8082/
paths:
  /rates:
    post:
      summary: レート履歴を新規登録します
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/History"
        required: true
      responses:
        "201":
          description: 登録成功
          content:
            application/json:
              schema:
                description: 成功時の情報
                type: object
                required:
                  - rateId
                  - expire
                properties:
                  rateId:
                    description: レート履歴ID
                    type: string
                  expire:
                    description: 有効期限
                    type: string
                    format: dateTime
        "400":
          description: 登録失敗（リクエストパラメータ不備）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: 登録失敗（通貨ペアが非対応）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: 登録失敗（内部エラー）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      tags:
        - rates
  /forecast/after5min/{rateId}:
    get:
      summary: 5分後の予想を取得します
      parameters:
        - name: rateId
          in: path
          required: true
          description: レート履歴ID
          schema:
            type: string
      responses:
        "200":
          description: 取得成功
          content:
            application/json:
              schema:
                description: 成功時の情報
                type: object
                required:
                  - rate
                properties:
                  result:
                    $ref: "#/components/schemas/ForecastResult"
        "404":
          description: 取得失敗（レート情報が見つからない）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: 取得失敗（内部エラー）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      tags:
        - rates
components:
  schemas:
    ForecastResult:
      description: 予測結果
      type: object
      required:
        - complete
      properties:
        complete:
          description: 予測が完了したか？
          type: boolean
        rate:
          description: レートの値
          type: number
          format: double
    History:
      description: レート履歴
      type: object
      required:
        - pair
        - rate_histories
      properties:
        pair:
          description: 通貨ペア
          type: string
          enum:
            - USDJPY
        rate_histories:
          type: array
          items:
            description: レートの履歴（先頭が過去）
            type: number
            format: double
    Error:
      description: エラー情報
      type: object
      required:
        - message
      properties:
        message:
          description: エラーメッセージ
          type: string
tags:
  - name: rates
    description: レート関連
