@startuml bin-option-rust

cloud gas [
    SpreadSheet
]
note left of gas
定期的に実行
end note

node server {
    database db {
        storage models [
            学習モデル
        ]
        storage rates [
            レート
        ]
    }

    agent ForecastServer

    agent RateGateway

    agent TrainingBatch
    note left of TrainingBatch
    定期的に実行
    end note
}

node local {
    agent MT4
}

models --> ForecastServer
ForecastServer --> MT4

models <--> TrainingBatch
rates -->TrainingBatch

gas --> RateGateway
RateGateway --> rates

@enduml
