@startuml bin-option-rust

cloud gas [
    SpreadSheet
]
note left of gas
定期的に実行
end note

node server {
    database db {
        storage models [
            学習モデル
        ]
        storage rates [
            レート（学習用）
        ]
        storage histories [
            レート（予測用）
        ]
        storage forecast [
            予測結果
        ]
    }

    agent ForecastServer

    agent ForecastBatch
    note left of ForecastBatch
    定期的に実行
    end note

    agent RateGateway

    agent TrainingBatch
    note left of TrainingBatch
    定期的に実行
    end note

    agent DataCleanBatch
    note left of DataCleanBatch
    定期的に実行
    end note
}

node local {
    agent MT4
}

histories <-- ForecastServer
models --> ForecastServer
forecast --> ForecastServer
ForecastServer <--> MT4

models --> ForecastBatch
histories --> ForecastBatch
forecast <-- ForecastBatch

models <--> TrainingBatch
rates -->TrainingBatch

gas --> RateGateway
RateGateway --> rates

DataCleanBatch --> rates
DataCleanBatch --> histories
DataCleanBatch --> forecast

@enduml
