openapi: "3.0.0"
info:
  version: 1.0.0
  title: RateGateway
  license:
    name: MIT
servers:
  - url: http://localhost:8081/
paths:
  /rates/{pair}:
    post:
      summary: レートを新規登録します
      parameters:
        - name: pair
          in: path
          required: true
          description: 通貨ペア
          schema:
            type: string
            enum:
              - USDJPY
      requestBody:
        content:
          application/json:
            schema:
              description: レートのリスト
              type: array
              items:
                $ref: "#/components/schemas/Rate"
        required: true
      responses:
        "201":
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostSuccess"
        "400":
          description: 登録失敗（リクエストパラメータ不備）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: 登録失敗（通貨ペアが非対応）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: 登録失敗（内部エラー）
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      tags:
        - rates
components:
  schemas:
    Rate:
      description: レート
      type: object
      required:
        - time
        - value
      properties:
        time:
          description: レートの日時
          type: string
          format: dateTime
        value:
          description: レートの値
          type: number
          format: double
    PostSuccess:
      description: Post成功時の情報
      type: object
      required:
        - count
      properties:
        count:
          description: 登録数
          type: integer
          format: int64
    Error:
      description: エラー情報
      type: object
      required:
        - message
      properties:
        message:
          description: エラーメッセージ
          type: string
tags:
  - name: rates
    description: レート関連
