name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --verbose

  build_rate_gateway:
    name: Build RateGateway
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        uses: ./.github/actions/build_image
        with:
          dockerfile: ./build/Dockerfile-rate-gateway
          tags: ghcr.io/${{ github.repository }}/rate-gateway:latest

  build_data_clean_batch:
    name: Build DataCleanBatch
    runs-on: ubuntu-latest
    needs: test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image
        uses: ./.github/actions/build_image
        with:
          dockerfile: ./build/Dockerfile-data-clean-batch
          tags: ghcr.io/${{ github.repository }}/data-clean-batch:latest
